DataDog/pupernetes

- environments/container-linux/ignition.yaml
Disable the reboot strategy managed by locksmithd.
Avoid a reboot during the tests.
> Disable the reboot strategy

- Makefile
- scripts/verify/docs.sh
- scripts/verify/license.sh
Improve the `Makefile` by moving all non file targets to `.PHONY`
Hide non user targets.
Simplify the rules.
> Refactor the Makefile

- RELEASE.md
- environments/container-linux/ignition.yaml
Ease the release process by adding a documentation for that.
Let everyone be able to submit a release.
It's a first step and I'm open to any workflow adapted to the size of this (small) project :smiley:
> Provide a release documentation

- RELEASE.md
- environments/container-linux/ignition.yaml
Update documentation and use SemVer
A brief description of the change being made with this pull request.
What inspired you to submit this pull request?
Anything else we should know when reviewing?
> Release 0.2.1

- .circleci/config.yml
The circle ci config contains a job executed over a virtual machine (ubuntu 14.04).
The workflow is split between jobs.
Improve the coverage of the PRs.
No milestones attached.
> Improve the circle CI configuration

- Gopkg.lock
- LICENSE-3rdparty.csv
- pkg/setup/secrets.go
- pkg/setup/templates/manifests.go
- vendor/github.com/hashicorp/go-sockaddr/.gitignore
- vendor/github.com/hashicorp/go-sockaddr/GNUmakefile
- vendor/github.com/hashicorp/go-sockaddr/LICENSE
- vendor/github.com/hashicorp/go-sockaddr/README.md
- vendor/github.com/hashicorp/go-sockaddr/doc.go
- vendor/github.com/hashicorp/go-sockaddr/ifaddr.go
- vendor/github.com/hashicorp/go-sockaddr/ifaddrs.go
- vendor/github.com/hashicorp/go-sockaddr/ifattr.go
- vendor/github.com/hashicorp/go-sockaddr/ipaddr.go
- vendor/github.com/hashicorp/go-sockaddr/ipaddrs.go
- vendor/github.com/hashicorp/go-sockaddr/ipv4addr.go
- vendor/github.com/hashicorp/go-sockaddr/ipv6addr.go
- vendor/github.com/hashicorp/go-sockaddr/rfc.go
- vendor/github.com/hashicorp/go-sockaddr/route_info.go
- vendor/github.com/hashicorp/go-sockaddr/route_info_bsd.go
- vendor/github.com/hashicorp/go-sockaddr/route_info_default.go
- vendor/github.com/hashicorp/go-sockaddr/route_info_linux.go
- vendor/github.com/hashicorp/go-sockaddr/route_info_solaris.go
- vendor/github.com/hashicorp/go-sockaddr/route_info_windows.go
- vendor/github.com/hashicorp/go-sockaddr/sockaddr.go
- vendor/github.com/hashicorp/go-sockaddr/sockaddrs.go
- vendor/github.com/hashicorp/go-sockaddr/unixsock.go
- vendor/github.com/hashicorp/vault/helper/parseutil/parseutil.go
This PR provide a dedicated certificate authority for the kube-controller-manager.
This new intermediate authority certificate is bundled with the root issuing CA.
This allows to submit and sign CSR via the Kubernetes API.
Be able to generate certificates with the Kubernetes API.
Use a more standard setup.
A upgraded the vault vendor and refactor the code.
> Use an intermediate Certificate Authority for cluster-signing

- environments/container-linux/ignition.yaml
Release the `pupernetes` v0.3.0
> release v0.3.0

- RELEASE.md
- environments/container-linux/ignition.yaml
* New wait command #43
* Use a more portable version of listUnits #44
> Release v0.4.0

- cmd/cli/cmd.go
Alias `pupernetes daemon` to `pupernetes d`
Feature requests from @CharlyF 👍
> Command line daemon alias

- .circleci/config.yml
- Makefile
- cmd/cli/cmd.go
- docs/pupernetes_daemon_run.md
- pkg/api/client.go
- pkg/config/config.go
- pkg/job/systemd.go
- pkg/logging/logging.go
- pkg/options/clean.go
- pkg/options/drain.go
- pkg/options/options.go
- pkg/run/delete.go
- pkg/run/getter.go
- pkg/run/run.go
- pkg/run/state.go
- pkg/run/stop.go
- pkg/setup/clean.go
- pkg/setup/getter.go
- pkg/setup/setup.go
- pkg/setup/systemd.go
- pkg/setup/templates/manifests.go
- pkg/wait/wait.go
Improve the project by using standard tools.
> Introduce ineffassign, golint and misspell

- README.md
- environments/container-linux/ignition.yaml
> Release v0.5.0

- pkg/job/systemd.go
Fix the job-type systemd when pupernetes is in PATH.
Fail before timeout if the systemd message is different than "done".
Propagate the `SUDO_USER` to let the user skip this kind of step:
```yaml
- run:
name: kubeconfig
command: mkdir -pv $HOME/.kube && touch $HOME/.kube/config
```
Fix #72 
Older systemd platforms don't manage the statusChan.
> Fix the abspath of pupernetes, propagate SUDO_USER to the unit env

- README.md
- environments/container-linux/ignition.yaml
- releasenotes.md
> Release v0.6.0

- .ci/pupernetes-validation.sh
- .ci/pupernetes-validation.yaml
- .circleci/config.yml
- .travis.yml
- README.md
- examples/circleci.yaml
- examples/travis.yaml
Create real examples to use pupernetes in SaaS CI.
The current CI configuration for pupernetes itself create noise around the testing of the project itself.
I seized this opportunity to improve the current CI system too.
> Refactor CI, introduce examples

- cmd/cli/cmd.go
- docs/pupernetes_daemon.md
- docs/pupernetes_daemon_clean.md
- docs/pupernetes_daemon_run.md
- docs/pupernetes_daemon_setup.md
- pkg/config/config.go
- pkg/setup/binary.go
- pkg/setup/setup.go
Make the timeout of download configurable.
Can SIG during a download and clean the partial downloaded archive.
Ease the usage when running pupernetes under a low internet bandwidth.
> Introduce a timeout and a sig handler during downloads

- pkg/setup/setup.go
Do create the directory for pod logs
Else it was getting missing when ran with specific settings, which then causes issues when trying to write to it.
> Do create the directory for pod logs

- README.md
> Fix a typo in the dig command

- .travis.yml
Fix the cache miss in travis when it expires (for nsenter)
> travis: fix when cache is missing

- .travis.yml
- README.md
- pkg/setup/templates/1.12.go
- pkg/setup/templates/manifests.go
Introduce the Kubernetes 1.12 release.
> Create Kubernetes 1.12 template collection

- README.md
Explain features and goals of pupernetes in README.
> Explain features and goals of pupernetes in README.

- RELEASE.md
- examples/circleci.yaml
- examples/travis.yaml
Upgrade the examples and add a note to the release process to keep them up to date.
> examples: upgrade to the latest pupernetes

- pkg/setup/templates/1.10.go
- pkg/setup/templates/1.11.go
- pkg/setup/templates/1.12.go
- pkg/setup/templates/1.9.go
A kill mode for control group doesn't make sense as we never want to kill the containers.
> containerd: kill move to process

- cmd/cli/cmd.go
- docs/pupernetes_daemon.md
- docs/pupernetes_daemon_clean.md
- docs/pupernetes_daemon_run.md
- docs/pupernetes_daemon_setup.md
- pkg/config/config.go
- pkg/setup/binary.go
- pkg/setup/setup.go
Allows to skip the verification of the version.
This is useful when debugging a component setup by pupernetes.
cc @nyodas
> binaries: can skip the verification of the version

- Makefile
- cmd/cli/cmd.go
- docs/pupernetes.md
- docs/pupernetes_daemon.md
- docs/pupernetes_daemon_clean.md
- docs/pupernetes_daemon_run.md
- docs/pupernetes_daemon_setup.md
- docs/pupernetes_reset.md
- docs/pupernetes_wait.md
- pkg/config/config.go
- version/version.go
Add a `--version` flag
Solve #67
> version: introduce the display of it

- cmd/cli/cmd.go
- docs/pupernetes_daemon.md
- docs/pupernetes_daemon_clean.md
- docs/pupernetes_daemon_run.md
- docs/pupernetes_daemon_setup.md
- pkg/config/config.go
- pkg/setup/secrets.go
- pkg/setup/setup.go
Configure the vault listen address during the setup stage.
> setup: can choose the vault listen address

- .travis.yml
- README.md
- pkg/setup/templates/1.14.go
- pkg/setup/templates/manifests.go
Add support for Kubernetes 1.14 in pupernetes.
> Add Kubernetes 1.14

- pkg/setup/templates/1.10.go
- pkg/setup/templates/1.11.go
- pkg/setup/templates/1.12.go
- pkg/setup/templates/1.13.go
- pkg/setup/templates/1.14.go
- pkg/setup/templates/1.8.go
- pkg/setup/templates/1.9.go
Increase the verbosity of the audit logs to all calls.
Being able to troubleshoot anything anywhere.
> setup: increase the verbosity of everything

- README.md
- environments/container-linux/ignition.yaml
- examples/circleci.yaml
- examples/travis.yaml
- releasenotes.md
* kube-apiserver: remove deprecated admission control flag #135
* setup: increase the verbosity of everything #133
* Update CNI #132
* Add Kubernetes 1.14 #130
* Fix systemd unit files #131
> release v0.10.0

- .circleci/config.yml
- .travis.yml
- README.md
- docs/pupernetes_daemon.md
- docs/pupernetes_daemon_clean.md
- docs/pupernetes_daemon_run.md
- docs/pupernetes_daemon_setup.md
- pkg/config/config.go
- pkg/run/state/notify.go
- pkg/setup/templates/1.10.go
- pkg/setup/templates/1.12.go
- pkg/setup/templates/1.13.go
- pkg/setup/templates/1.14.go
- pkg/setup/templates/1.15.go
- pkg/setup/templates/1.16.go
- pkg/setup/templates/1.17.go
- pkg/setup/templates/1.18.go
- pkg/setup/templates/1.5.go
- pkg/setup/templates/1.6.go
- pkg/setup/templates/1.7.go
- pkg/setup/templates/1.8.go
- pkg/setup/templates/1.9.go
- pkg/setup/templates/manifests.go
Support Kubernetes 1.18
Upgrade to the latest etcd 3 version
Upgrading the go version
> hyperkube: create 1.18

- Makefile
- README.md
- RELEASE.md
- environments/container-linux/ignition.yaml
- examples/circleci.yaml
- examples/travis.yaml
- releasenotes.md
* Add Kubernetes 1.18 #139
* Fix a race condition when downloading pupernetes #142
> Release v0.12.0
