pkg/setup/kubeclient.go
pkg/setup/setup.go

When restarting a systemd unit with `--kubectl-link`, it fail.
Avoid any additional logic outside of pupernetes like:
```text
ExecStartPre=-/bin/rm -v /opt/bin/kubectl
```
When the link is already created and valid, it doesn't fail.
Improve the integration in the testing instances.

Don't fail if the kubectl link is already here

---

pkg/setup/kubeclient.go

The logging message isn't the used configuration file.

Display the adapted config in the logs

---

pkg/run/notify.go

Adapt the severity when the Parent PID isn't PID 1 (systemd).

Change the severity of the notify when not running in systemd unit

---

docs/pupernetes.md
docs/pupernetes_clean.md
docs/pupernetes_run.md
docs/pupernetes_setup.md
pkg/config/config.go
pkg/run/run.go
pkg/run/state.go
pkg/setup/clean.go
pkg/setup/setup.go

* remove by default the `/var/log/pods` directory
* provide more logs before being ready
* provide the number of pods in CRI log-dir `/var/log/pods`
```text
I0525 19:50:19.463448    5878 clean.go:32] Removed /home/jb/go/src/github.com/DataDog/pupernetes/sandbox/etcd-data
I0525 19:50:19.487854    5878 clean.go:32] Removed /var/lib/p8s-kubelet
I0525 19:50:19.579110    5878 clean.go:32] Removed /var/log/pods
I0525 19:50:19.579140    5878 clean.go:144] Cleanup successfully finished
I0525 19:50:19.659453    5878 hostname.go:59] Using hostname: "haf"
I0525 19:50:22.352439    5878 setup.go:272] Setup ready /home/jb/go/src/github.com/DataDog/pupernetes/sandbox
I0525 19:50:22.352673    5878 run.go:71] Timeout for this current run is 6h0m0s
I0525 19:50:22.352699    5878 systemd.go:40] Starting …
```

Display more state of the runtime

---

.circleci/config.yml
cmd/cli/cmd.go
docs/pupernetes.md
docs/pupernetes_daemon.md
docs/pupernetes_daemon_clean.md
docs/pupernetes_daemon_run.md
docs/pupernetes_daemon_setup.md
docs/pupernetes_reset.md
pkg/api/api.go
pkg/api/client.go
pkg/config/config.go
pkg/run/delete.go
pkg/run/run.go
pkg/run/stop.go
pkg/setup/binary.go

All the already existing commands are under the `daemon` sub commands.
Introduce the `reset`command to reset Kubernetes namespaces and re-deploy the initial manifests.
Ease the flow when running multiple argo workflows.
This allows to not implementing the deletion in each argo workflow.
```bash
pupernetes reset default
```
The default namespace can also be reset with:
```bash
pupernetes reset kube-system --apply
```
All namespaces can also be reset with:
```bash
pupernetes reset $(kubectl get ns -o name) --apply
```
Or with a SIGSTP:
```
sudo ./pupernetes daemon run sandbox/
I0605 12:10:29.656861   10858 clean.go:32] Removed /home/jb/go/src/github.com/DataDog/pupernetes/sandbox/etcd-data
I0605 12:10:29.657341   10858 clean.go:32] Removed /var/lib/p8s-kubelet
I0605 12:10:29.657991   10858 …
```

Introduce the daemon and the reset commands

---

cmd/cli/cmd.go
docs/pupernetes.md
docs/pupernetes_wait.md
pkg/config/config.go
pkg/wait/wait.go

This new command remove any logic like: 
```bash
until curl -sf http://127.0.0.1:8989/ready --connect-timeout 1 -w '\n'
do
systemctl status pupernetes.service --no-pager --full
journalctl -u pupernetes.service --no-pager -o cat -n 50 -e
sleep 10
done
```
to be used like:
```bash
pupernetes wait pupernetes.service
```
This will nicely tail the associated journald entry without any duplicate.
```text
[pupernetes.service] Starting github.com/DataDog/pupernetes...
[pupernetes.service] I0607 18:05:25.886126   27882 clean.go:32] Removed /home/jb/go/src/github.com/DataDog/pupernetes/sanbox/etcd-data
[pupernetes.service] I0607 18:05:25.886537   27882 clean.go:32] Removed /var/lib/p8s-kubelet
[pupernetes.service] I0607 18:05:25.886567   27882 clean.go:32] Removed /var/log/pods/ …
```

New wait command

---

pkg/job/systemd.go
pkg/run/probe.go
pkg/setup/manifests.go
pkg/setup/systemd.go
pkg/util/systemd_action.go
pkg/wait/wait.go

The method `ListUnitsByNames` only supports a systemd >= 230.
See https://github.com/coreos/go-systemd/issues/223
I used the generic ListUnits and @xvello tested it on systemd 229 👍 
I also added the systemd prefix to the units in the manifests:
```
sandbox/manifest-systemd-unit/p8s-etcd.service
sandbox/manifest-systemd-unit/p8s-kube-apiserver.service
sandbox/manifest-systemd-unit/p8s-kubelet.service
```
Because the link in `/run/systemd/system/p8s-kubelet.service` -> `~/sandbox/manifest-systemd-unit/kubelet.service`
Give an unit name `kubelet.service` instead of `p8s-kubelet.service`

Use a more portable version of listUnits

---

environments/container-linux/ignition.yaml

Set by default the systemd notify in the unit.
Needed by `pupernetes wait` possible with #16 #34

Add notify to the systemd unit

---

README.md

Add SaaS CI examples to run `pupernetes`.
Add status badges :sun_with_face: 
Ease the adoption of `pupernetes`

Add SaaS CI examples

---

pkg/run/run.go
pkg/run/stop.go
pkg/util/systemd_action.go

Defer the `signal.Reset` isn't appropriate because it doesn't allow to skip the Kubelet GC as before.
This PR fix this regression

Fix the signal reset on SIGs during Stop

---

README.md
pkg/setup/requirements.go
pkg/setup/secrets.go

#51 
Use Go's RSA standard library instead of executing `openssl`.
Less dependencies.

Use RSA standard library

---

cmd/cli/cmd.go
docs/pupernetes_daemon.md
docs/pupernetes_daemon_clean.md
docs/pupernetes_daemon_run.md
docs/pupernetes_daemon_setup.md
docs/pupernetes_reset.md
docs/pupernetes_wait.md
pkg/api/client.go
pkg/config/config.go
pkg/run/run.go
pkg/setup/getter.go

Multiple timeouts referenced a single viper entry.
This discard any user input value.
I added a customisable timeout for the reset command. 
I removed few viper calls from the run package see #40

Use a dedicated timeout for each package

---

README.md
pkg/setup/templates/1.10.go
pkg/setup/templates/1.11.go

Specifying flags to enable the registering and support of Metrics Server and Custom/External Metrics Provider.
Create an HPA ready cluster locally. Allow to register the EM providers.
Verified for:

Enable HPA

---

.ci/sonobuoy.sh
.circleci/config.yml
cmd/cli/cmd.go
docs/pupernetes_daemon.md
docs/pupernetes_daemon_clean.md
docs/pupernetes_daemon_run.md
docs/pupernetes_daemon_setup.md
pkg/config/config.go
pkg/setup/kubeclient.go
pkg/setup/setup.go
pkg/setup/systemd.go

Introduce [sonobuoy](https://github.com/heptio/sonobuoy) in the CI pipeline
Use existing tools to validate the Kubernetes setup.
The `Quick` does not implement a lot of tests.
Along the way, I found convenient to add a `--kubeconfig-path` flag as an alternative to the behaviour around the `$SUDO_USER`

Introduce sonobuoy in CI

---

pkg/setup/binary.go
pkg/setup/binary_cni.go
pkg/setup/binary_etcd.go
pkg/setup/binary_hyperkube.go
pkg/setup/binary_vault.go

During the setup/binaries stage, if the download is interrupted by the user, the file isn't completed.
When retrying to run the pupernetes commands, it continuously fail if you don't clean the binaries.
I propose to automatically removes the archive when it cannot extract the binary from it:
```text
sudo ./pupernetes d setup sandbox/ -c -binaries
W0626 20:59:04.344539    9005 clean.go:74] Cannot use kubectl: stat /home/jb/go/src/github.com/DataDog/pupernetes/sandbox/bin/hyperkube: no such file or directory
I0626 20:59:04.349950    9005 systemd_action.go:123] Stopping p8s-etcd.service ...
E0626 20:59:04.351226    9005 systemd_action.go:74] Cannot execute systemd action on p8s-etcd.service: Unit p8s-etcd.service not loaded.
E0626 20:59:04.351600    9005 clean.go:134] Cannot stop systemd …
```

Remove the archive on extract failure

---

pkg/setup/templates/1.10.go
pkg/setup/templates/1.11.go
pkg/setup/templates/1.5.go
pkg/setup/templates/1.6.go
pkg/setup/templates/1.7.go
pkg/setup/templates/1.8.go
pkg/setup/templates/1.9.go

Remove the duplicated configuration flag in the kubelet.

Remove the duplicated flag in manifests

---

pkg/run/stop.go
pkg/setup/clean.go
pkg/setup/setup.go

The units are started in the following order:
* etcd
* kube-apiserver
* kubelet
It's better to stop them in a reverse order because when the kube-apiserver loose the access to the etcd, it increases the CPU usage.
I also changed the initial order to start the kube-apiserver before the kubelet.
This change is needed when using Kubelet TLS Bootstrap as the Kubelet needs the kube-apiserver.
To use the TLS Bootstrap, the controller-manager can't be containerised because it's required to issue the certificates.

Stop the systemd units in a reverse order

---

.travis.yml

Introduce the Kubernetes 1.11.0 release in the default travis pipeline matrix.

Add hyperkube 1.11

---

README.md

Updated the README to add a new requirement.
`sudo ./pupernetes daemon run sandbox/` does not work otherwise.

Fixed README and added new subsection for DNS requirement

---

RELEASE.md
releasenotes.md

Introduce the release note.
Improve the release process to validate the release notes.
I have to update all releases to stay coherent.

Introduce release notes

---

.circleci/config.yml
pkg/run/readiness.go
pkg/run/run.go

After #73, I introduced a regression when using `pupernetes reset $ns --apply` or `SIGSTP`.
The `re-apply` feature doesn't work anymore.
To avoid this kind of regression I added a test in the CI.
This should be short released on `v0.6.1`.

Fix the re-apply system

---

cmd/main.go
pkg/setup/requirements/requirements.go

Fix a missing log in the setup stage.
When starting a setup without being root, the command fails without any log.
```text
./pupernetes daemon run /opt/new-dir
I0704 19:00:37.405322   24527 clean.go:165] Cleanup finished
E0704 19:00:37.406233   24527 main.go:27] Exiting on error: 1
```
```text
./pupernetes daemon run /opt/new-dir
I0704 19:00:37.405322   24527 clean.go:165] Cleanup finished
E0704 19:00:37.405496   24527 requirements.go:53] Requirement failure: must run as root
E0704 19:00:37.406233   24527 main.go:27] Exiting on error: 1
```

Logging improvements on setup requirements

---

.circleci/config.yml
.travis.yml
Makefile
RELEASE.md
scripts/update/license.sh

Improve the circle CI workflow as suggested in #86 
Don't start machine executor if the build failed.
Use golang 1.10 everywhere: build pupernetes from `docker://golang:1.10`.
To attempt to cache the pupernetes directory, I tried to use:
* persist_to_workspace
* attach_workspace
But I get the following error in the machine executor:
```text
Downloading workspace layers
workflows/workspaces/971cef4a-2eae-441e-a45a-2aa4275d8612/0/5611dc91-3ef1-443b-9c59-922beca7d436/0/108.tar.gz - 21 MB
Applying workspace layers
5611dc91-3ef1-443b-9c59-922beca7d436
Error applying workspace layer for job 5611dc91-3ef1-443b-9c59-922beca7d436: Error extracting tarball /tmp/workspace-layer-5611dc91-3ef1-443b-9c59-922beca7d436241049481: exit status 2
```
See:
* …

Improve circleci

---

pkg/setup/templates/1.10.go
pkg/setup/templates/1.11.go

Switch to the configuration file instead of files.
Flags are deprecated to these versions.

Use kube proxy configuration file

---

README.md

Change current k8s version compatibility in README
1.5 and 1.6 are not yet functional https://github.com/DataDog/pupernetes/blob/master/.travis.yml#L19

Change current k8s version compatibility in README

---

pkg/setup/secrets.go
pkg/setup/templates/1.10.go
pkg/setup/templates/1.11.go
pkg/setup/templates/1.5.go
pkg/setup/templates/1.6.go
pkg/setup/templates/1.7.go
pkg/setup/templates/1.8.go
pkg/setup/templates/1.9.go

Enable the Kubernetes 1.9 api aggregation.
This PR removes the intermediate certificate authority provided in the kube-controller-manager flags.
This is a major enhancement  and should be released soon.

API aggregation, remove intermediate CA

---

cmd/cli/cmd.go
docs/pupernetes_daemon_run.md
pkg/config/config.go
pkg/run/readiness.go
pkg/run/run.go
pkg/run/stop.go

Skip probe allows to discard any failure of the environment.
This is very useful while iterating on kubernetes components (configuration or master dev).
I moved all the parameters to a dedicated config structure.
The name of the flag could also be something like `ignore-probe`

Introduce skip probe

---

docs/pupernetes_daemon_run.md
pkg/config/config.go
pkg/run/run.go

Remove the default (7 hours) timeout
We already have to set a shorter timeout when using the CI and the default timeout can be annoying in dev env where you could you lose some configuration.

Remove default timeout

---

pkg/setup/templates/1.10.go
pkg/setup/templates/1.11.go
pkg/setup/templates/1.8.go
pkg/setup/templates/1.9.go

Remove useless stage in audit logs
Less apiserver audit logs, less cpu and disk access

Remove useless stage in audit logs

---

pkg/setup/templates/1.10.go
pkg/setup/templates/1.11.go
pkg/setup/templates/1.8.go
pkg/setup/templates/1.9.go

The previous configuration only logs the core/v1 calls.
By removing the resource, it logs everything.
I also added the content of the events when they are created.

Extend the audit logs to everything

---

.circleci/config.yml
cmd/cli/cmd.go
docs/pupernetes_daemon.md
docs/pupernetes_daemon_clean.md
docs/pupernetes_daemon_run.md
docs/pupernetes_daemon_setup.md
pkg/config/config.go
pkg/options/clean.go
pkg/options/clean_test.go
pkg/options/drain.go
pkg/options/options.go
pkg/setup/setup.go

Replace the non documented `--clean -binaries`
Add a quicker way to plays with the options.

Introduce the keep verb

---

docs/pupernetes_daemon.md
docs/pupernetes_daemon_clean.md
docs/pupernetes_daemon_run.md
docs/pupernetes_daemon_setup.md
pkg/config/config.go
pkg/setup/setup.go

I upgraded the current versions of etcd, containerd and hyperkube.
coreos moved etcd to `etcd-io/etcd`

versions: upgrade hyperkube, etcd and containerd

---

cmd/cli/cmd.go
docs/pupernetes_daemon.md
docs/pupernetes_daemon_clean.md
docs/pupernetes_daemon_run.md
docs/pupernetes_daemon_setup.md

The configuration already existed but wasn't exposed over the command line.

containerd: can choose the version over the command line

---

Makefile

Allows to build with go version 1.10+

makefile: set the constrain to go 1.10+

---

pkg/setup/templates/1.13.go
pkg/setup/templates/manifests.go

Introduce Kubernetes 1.13 in pupernetes.
The scheduler is now responsible to start daemonsets, so it's not possible anymore to use the controller manager to start a scheduler as daemonset.

add kubernetes 1.13

---

pkg/setup/templates/1.10.go
pkg/setup/templates/1.11.go
pkg/setup/templates/1.12.go

This PR adds the support of the shared process namespace.
It allows to send signals from a container/task in an another one, as long they're in the same Pod.
This is needed to create a certificate renew story.
This is available at the pod's spec level.

node: support shared PID

---

README.md
environments/container-linux/ignition.yaml
examples/circleci.yaml
examples/travis.yaml
releasenotes.md

* node: support shared PID #128
* add kubernetes 1.13 #126
* setup: can choose the vault listen address #125
* version: introduce the display of it #121
* containerd: can choose the version over the command line #122
* binaries: can skip the verification of the version #120
* Support Fedora (systemd cgroupfs) #118
* versions: upgrade hyperkube, etcd and containerd #116
* resolv: remove the extension .conf #117
* containerd: kill move to process #115
* bump travis matrix #127
* makefile: set the constrain to go 1.10+ #123
* Update the license file #119
* examples: upgrade to the latest pupernetes #114

release: v0.9.0

---

pkg/setup/templates/1.10.go
pkg/setup/templates/1.11.go
pkg/setup/templates/1.12.go
pkg/setup/templates/1.13.go
pkg/setup/templates/1.14.go
pkg/setup/templates/1.5.go
pkg/setup/templates/1.6.go
pkg/setup/templates/1.7.go
pkg/setup/templates/1.8.go
pkg/setup/templates/1.9.go

Fix `ExecStart` directives in systemd unit files.
When testing on Ubuntu 19.04, I came accross this:
```
E0502 13:53:07.817833    7613 probe.go:50] Unexpected state of: unit "p8s-etcd.service" with load state "loaded" is "failed"
E0502 13:53:07.819015    7613 probe.go:50] Unexpected state of: unit "p8s-kubelet.service" with load state "loaded" is "failed"
```
Relevant journald logs show:
```
[p8s-etcd.service] error verifying flags, 'Restart=no' is not a valid flag. See 'etcd --help'.
[p8s-kubelet.service] F0502 13:53:05.893647    7807 server.go:154] unknown command: Restart=no
```
It looks like the syntax was off and systemd got less permissive.

Fix systemd unit files

---

environments/container-linux/ignition.yaml

Fix a race condition when downloading pupernetes
It happens that from time to time, we see failures likes this:
```
waiting for pupernetes binary to be in PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/bin ...
+ sudo -kE pupernetes wait --unit-to-watch pupernetes.service --logging-since 2h --wait-timeout 20m
sudo: pupernetes: command not found
+ sleep 10
+ sudo -kE pupernetes wait --unit-to-watch pupernetes.service --logging-since 2h --wait-timeout 20m
sudo: pupernetes: command not found
+ exit 1
Running after_script
00:01
Uploading artifacts for failed job
00:01
ERROR: Job failed: exit code 1
```
Anything else we should know when reviewing?

Fix a race condition when downloading pupernetes
